# Generated by Django 5.0.3 on 2024-04-14 09:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avg_profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('custom_avg_profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('current_custom_profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('about', models.TextField()),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('max_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('total_copiers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='trader.trader')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyProfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='strategy.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='UserOutStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('date_of_adding', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_out', models.DateTimeField(auto_now_add=True)),
                ('profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_users', to='strategy.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_strategies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('date_of_adding', models.DateTimeField(auto_now_add=True)),
                ('profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('saved_profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('custom_profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('different_profit_from_strategy', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('current_custom_profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='strategy.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'strategy')},
            },
        ),
    ]
