# Generated by Django 5.0.3 on 2024-03-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avg_profit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('about', models.TextField()),
                ('total_deposited', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('min_deposit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('max_deposit', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='trader.trader')),
            ],
        ),
    ]
