# Generated by Django 5.0.3 on 2024-03-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
        ('trader', '0002_remove_trader_email_remove_trader_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='trader.trader'),
        ),
    ]
