# Generated by Django 5.0.3 on 2024-04-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='saved_avg_profit',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
    ]
