# Generated by Django 5.0.3 on 2024-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinstrategy',
            name='different_profit_from_strategy',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='usersinstrategy',
            name='saved_profit',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
    ]
