# Generated by Django 5.0.3 on 2024-03-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_alter_strategy_trader'),
        ('trader', '0003_alter_trader_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='trader.trader'),
        ),
    ]
