# Generated by Django 5.0.3 on 2024-03-19 20:08

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_alter_strategy_trader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinstrategy',
            name='date_of_adding',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 19, 20, 8, 34, 700116, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usersinstrategy',
            unique_together={('user', 'strategy')},
        ),
    ]
