# Generated by Django 5.0.3 on 2024-03-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_usersinstrategy_date_of_adding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='total_copiers',
            field=models.IntegerField(default=0),
        ),
    ]
