# Generated by Django 5.0.3 on 2024-06-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_alter_usersinstrategy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutstrategy',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
