# Generated by Django 5.0.3 on 2024-06-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_alter_useroutstrategy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroutstrategy',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
