# Generated by Django 5.0.3 on 2024-03-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_strategy_total_copiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='current_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='custom_avg_profit',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='strategy',
            name='max_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
