# Generated by Django 5.0.3 on 2024-03-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_strategy_current_users_strategy_custom_avg_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='current_users',
        ),
    ]
