# Generated by Django 5.0.3 on 2024-03-26 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0009_strategy_current_custom_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyProfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='strategy.strategy')),
            ],
        ),
    ]
