# Generated by Django 5.0.3 on 2024-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0011_usersinstrategy_profit_useroutstrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinstrategy',
            name='current_custom_profit',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='usersinstrategy',
            name='custom_profit',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
    ]
