# Generated by Django 5.0.3 on 2024-04-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0013_alter_strategy_max_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='max_users',
        ),
    ]
