# Generated by Django 5.0.3 on 2024-04-12 07:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_pair', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('short', 'short'), ('long', 'long')], default='long', max_length=10)),
                ('open_price', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('close_price', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('close_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('roi', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.trader')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('side', models.BooleanField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.trader')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('side', models.CharField(choices=[('deposit', 'DEPOSIT'), ('withdraw', 'WITHDRAW')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
