# Generated by Django 5.0.3 on 2024-03-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_pair', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=7, max_digits=30)),
                ('amount', models.DecimalField(decimal_places=7, max_digits=30)),
                ('side', models.BooleanField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.trader')),
            ],
        ),
    ]
