# Generated by Django 5.0.3 on 2024-04-15 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionclose',
            name='open_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
