# Generated by Django 5.0.3 on 2024-03-20 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_trader_avg_profit_strategies'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('side', models.BooleanField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.trader')),
            ],
        ),
    ]
