# Generated by Django 5.0.3 on 2024-04-13 15:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_usersinstrategy_different_profit_from_strategy_and_more'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_pair', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('short', 'long'), ('long', 'long')], default='long', max_length=10)),
                ('open_price', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('close_price', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('close_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('roi', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_pair', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('short', 'long'), ('long', 'long')], default='long', max_length=10)),
                ('open_price', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('open_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
