# Generated by Django 5.0.3 on 2024-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactionclose_open_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionclose',
            old_name='total_value',
            new_name='percentage',
        ),
        migrations.RenameField(
            model_name='transactionopen',
            old_name='total_value',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='transactionclose',
            name='value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='transactionopen',
            name='value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
    ]
