# Generated by Django 5.0.3 on 2024-04-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_transaction_amount_remove_transaction_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='avg_open_price',
            new_name='open_price',
        ),
    ]
