# Generated by Django 5.0.3 on 2024-04-14 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('about', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trader_photos')),
                ('avg_profit_strategies', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_copiers', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('copiers_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('visible', models.BooleanField(default=False)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('profit_to_loss_ratio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('weekly_trades', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('avg_holding_time', models.CharField(default='No info', max_length=20)),
                ('roi_volatility', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('last_traded_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraderProfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='trader.trader')),
            ],
        ),
    ]
