# Generated by Django 5.0.3 on 2024-03-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='password',
        ),
        migrations.AddField(
            model_name='trader',
            name='about',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trader',
            name='photo',
            field=models.ImageField(blank=True, upload_to='trader_photos'),
        ),
    ]
