# Generated by Django 5.0.3 on 2024-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_remove_trader_email_remove_trader_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
