# Generated by Django 5.0.3 on 2024-04-27 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_trader_trader_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='available_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
