# Generated by Django 5.0.3 on 2024-04-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_trader_available_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
