# Generated by Django 5.0.3 on 2024-03-24 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_trader_avg_profit_strategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='avg_holding_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='last_traded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trader',
            name='profit_to_loss_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='roi_volatility',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='sharpe_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='sortino_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='weekly_trades',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
