# Generated by Django 5.0.3 on 2024-04-29 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_trendingthreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingthreshold',
            name='min_copiers',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
