# Generated by Django 5.0.3 on 2024-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_alter_trader_avg_holding_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='followers_count',
        ),
        migrations.AddField(
            model_name='trader',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UsersFollowsTrader',
        ),
    ]
