# Generated by Django 5.0.3 on 2024-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_remove_trader_followers_count_trader_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='win_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
