# Generated by Django 5.0.3 on 2024-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_alter_trader_avg_holding_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='max_copiers',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trader',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='last_traded_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trader',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trader_photos'),
        ),
    ]
