# Generated by Django 5.0.3 on 2024-04-11 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_trader_max_copiers_alter_trader_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='max_copiers',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
