# Generated by Django 5.0.3 on 2024-03-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=7, max_digits=30)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto', to='strategy.strategy')),
            ],
        ),
    ]
