# Generated by Django 5.0.3 on 2024-03-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
    ]
