# Generated by Django 5.0.3 on 2024-03-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_cryptoinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoinuser',
            name='total_value',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
