# Generated by Django 5.0.3 on 2024-04-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_crypto_side_cryptoinuser_side_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='deposited_value',
        ),
    ]
