# Generated by Django 5.0.3 on 2024-04-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_alter_crypto_side_alter_crypto_total_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPriceHistory24h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('highest_price', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('lowest_price', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
            ],
        ),
    ]
