# Generated by Django 5.0.3 on 2024-04-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_cryptopricehistory24h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='exchange_rate',
        ),
        migrations.DeleteModel(
            name='CryptoInUser',
        ),
    ]
